server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/api/tariffs/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/api/groups/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/api/frequents/**
        - id: ms4
          uri: lb://ms4
          predicates:
            - Path=/api/special/**
        - id: ms5
          uri: lb://ms5
          predicates:
            - Path=/api/reservations/**
        - id: ms6
          uri: lb://ms6
          predicates:
            - Path=/api/racks/**
