# filepath: c:\Users\Public\Desktop\Tingeso2\config-data\ms1.yml
spring:
  application:
    name: ms1         # <— obligatorio para que Eureka lo registre como “ms1”
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}