apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: isirm/frontend:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-confi
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - name: nginx-confi
          configMap:
            name: frontend-nginx-cm
