apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ms4
  name: ms4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms4
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ms4
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
          image: isirm/ms4:latest
          imagePullPolicy: IfNotPresent
          name: ms4
      restartPolicy: Always
