apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_MULTIPLE_DATABASES: ms1db,ms2db,ms3db,ms4db,ms5db,ms6db,ms7db